# Generated by Django 2.1.1 on 2018-09-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OR', models.CharField(max_length=15)),
                ('order_date', models.DateTimeField()),
                ('raw_total_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=150, max_digits=6)),
                ('total_price', models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, default=150, max_digits=6), max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=200, unique=True)),
                ('barcode', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/%Y/%m/%D/')),
                ('number_of_stocks', models.IntegerField(default=0)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('category', models.ManyToManyField(default=None, to='musicstoreadmin.Category')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(default=None, to='musicstoreadmin.Product'),
        ),
    ]
