# Generated by Django 2.1.1 on 2018-09-27 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicstoreadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=500, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
