# Generated by Django 2.1.1 on 2018-10-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicstoreadmin', '0002_auto_20180927_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
