# Generated by Django 2.1.1 on 2018-10-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicstoreadmin', '0003_useraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
