# Generated by Django 2.1.1 on 2018-10-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicstoreadmin', '0007_auto_20181021_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='musicstoreadmin.Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
